plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.linkedinmediadownloader'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.linkedinmediadownloader'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a'
            universalApk false
        }
    }
}
